sudo: required
services:
  - docker       #travis cli needs docker cli to be installed. docker cli needs a copy of docker to run
before_install:
  - docker build -t irarelycode/docker-react -f Dockerfile.dev .  #runs before deploying the project
script:   #commands needed to run test suites,all commands below this needs to be 
  - docker run -e CI=true irarelycode/docker-react npm run test -- --coverage
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env:  "docker-react-env"
#   bucket_name:  "elasticbeanstalk-us-west-2-304383927493402"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id:  $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"      


# set these keys in iAM service of aws 